/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PARCIAL2.sistema;


import PARCIAL2.conexion;
import PARCIAL2.ExportarExcel;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;


/**
 *
 * @author braya
 */
public class productos extends javax.swing.JInternalFrame {

    
      conexion con1=new conexion();
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
   
    double suma=0;
    
    
    /**
     * Creates new form productos
     */
    public productos() {
        initComponents();
         consultar();
        
        txid.setVisible(false);
        

        Tabla.addMouseListener(new MouseAdapter(){
        public void mousePressed(MouseEvent Mouse_evt)
                {
                JTable table=(JTable) Mouse_evt.getSource();
                Point point= Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if(Mouse_evt.getClickCount()==1)
                {
                        
                
               
                
                txid.setText(Tabla.getValueAt(Tabla.getSelectedRow(),0).toString());
                txtnombre.setText(Tabla.getValueAt(Tabla.getSelectedRow(),1).toString());
                txtprecio.setText(Tabla.getValueAt(Tabla.getSelectedRow(),2).toString());
                txtcantidad.setText(Tabla.getValueAt(Tabla.getSelectedRow(),3).toString());
               txtmarca.setText(Tabla.getValueAt(Tabla.getSelectedRow(),4).toString());
                }    
                
                }
        
        });
        
      

        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtgrantotal = new javax.swing.JLabel();
        txid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        txtmarca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PARCIAL2/iconos/writing_ruler_education_school_box_pencil_material_office_utensils_tools_icon_256490.png"))); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Gran Total :");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PARCIAL2/iconos/delete_garbage_bin_trash_remove_icon_256469.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtgrantotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtgrantotal.setText("Q 00.00 ");

        txid.setText("ID:");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Precio", "Cantidad", "Marca", "SubTotal", "Fecha modificación"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        jPanel3.setBackground(new java.awt.Color(24, 186, 199));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("HOME SOUND SOLUTIONS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(323, 323, 323))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Precio:");

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PARCIAL2/iconos/copia (1).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad:");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Marca:");

        agregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PARCIAL2/iconos/annual_calender_day_schedule_date_time_calendar_icon_256474.png"))); // NOI18N
        agregar.setText("Guardar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PARCIAL2/iconos/archieve_storage_files_documents_folder_icon_256481.png"))); // NOI18N
        jButton1.setText("Exportar a Excel . XMLS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgrantotal)
                        .addGap(217, 217, 217))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtprecio)
                            .addComponent(txtcantidad)
                            .addComponent(txtmarca))
                        .addGap(30, 30, 30)
                        .addComponent(jButton4)
                        .addGap(237, 237, 237)
                        .addComponent(txid)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txid)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4)
                    .addComponent(txtgrantotal))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modificar();
        consultar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        eliminar();
        consultar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtnombre.setText("");
        txtcantidad.setText("");
        txtprecio.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        agregar();
        consultar();

    }//GEN-LAST:event_agregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /* ExportarExcel obj;
        try{
            obj=new ExportarExcel();
            obj.exportarExcel(Tabla);
        }catch(Exception e){
            System.out.println("Error: "+e);

        }*/
       
      //prueba pdf
      try{
    FileOutputStream archivo;
    File file= new File("src/pdf/Productos.pdf");
    archivo= new FileOutputStream(file);
    Document doc = new Document();
    PdfWriter.getInstance(doc, archivo);
    doc.open();
    Image img = Image.getInstance("C:\\Users\\braya\\Documents\\NetBeansProjects\\PIIB\\build\\classes\\PARCIAL2\\iconos\\copia.png");
    
    Paragraph fecha = new Paragraph();
    Font negrita= new Font(Font.FontFamily.TIMES_ROMAN,12, Font.BOLD,BaseColor.BLUE);
    fecha.add(Chunk.NEWLINE);
    Date date=new Date();
    fecha.add("Fecha: "+ new SimpleDateFormat("dd-mm-yyyy").format(date)+"\n\n");
    
    //numero de columas
    PdfPTable Encabezado = new PdfPTable(4);
    //tamano del encabezado 100 es toda la hoja
    Encabezado.setWidthPercentage(100);
    //sin bordes =0
    Encabezado.getDefaultCell().setBorder(0);
    //tamano de las celdas
    float[] ColumnaEncabezado = new float[]{20f,40f,70f,40f};
    //pasamos las columnas al encabezado
    Encabezado.setWidths(ColumnaEncabezado);
    Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
    
    Encabezado.addCell(img);
    
    //datos de la empresa 
    
   String nit ="1111111111111";
   String nom="SOUND SOLUTIONS";
   String tel="11111111";
   String dir="Chimaltenango";
   String ra="Hola Mundo";
    
   Encabezado.addCell("");
   Encabezado.addCell("Ruc :"+nit+"\nNombre: "+nom+"\nTelefono: "+tel+"\nDireccion: "+dir+"\nRazon: "+ra);
   Encabezado.addCell(fecha);
   doc.add(Encabezado);
    
    
   Paragraph cli = new Paragraph();
   cli.add(Chunk.NEWLINE);
   cli.add("Datos del Productos"+"\n\n");
   doc.add(cli);
  
   
    //tabla producto formato
   //numro de columnas
   PdfPTable tablapro = new PdfPTable(6);
    //tamano del encabezado 100 es toda la hoja
    tablapro.setWidthPercentage(100);
    //sin bordes =0
    tablapro.getDefaultCell().setBorder(0);
    //tamano de las celdas
    float[] Columnapro = new float[]{10f,50f,15f,15f,15f,20f};
    //pasamos las columnas al encabezado
    tablapro.setWidths(Columnapro);
    //alineacion de la columna
    tablapro.setHorizontalAlignment(Element.ALIGN_LEFT);
   
    PdfPCell pro1 = new PdfPCell(new Phrase("id",negrita));
    PdfPCell pro2 = new PdfPCell(new Phrase("nombre",negrita));
    PdfPCell pro3 = new PdfPCell(new Phrase("Precio U.",negrita));
    PdfPCell pro4 = new PdfPCell(new Phrase("Cantidad",negrita));
    PdfPCell pro5 = new PdfPCell(new Phrase("Subtotal",negrita));
    PdfPCell pro6 = new PdfPCell(new Phrase("Marca",negrita));
    
    
    pro1.setBorder(0);
    pro2.setBorder(0);
    pro3.setBorder(0);
    pro4.setBorder(0);
    pro5.setBorder(0);
 pro6.setBorder(0);
    //colores para las columnas
    pro1.setBackgroundColor(BaseColor.LIGHT_GRAY);
    pro2.setBackgroundColor(BaseColor.LIGHT_GRAY);
    pro3.setBackgroundColor(BaseColor.LIGHT_GRAY);
    pro4.setBackgroundColor(BaseColor.LIGHT_GRAY);
     pro5.setBackgroundColor(BaseColor.LIGHT_GRAY);
    pro6.setBackgroundColor(BaseColor.LIGHT_GRAY);
    
    
    tablapro.addCell(pro1);
    tablapro.addCell(pro2);
    tablapro.addCell(pro3);
    tablapro.addCell(pro4);
    tablapro.addCell(pro5);
    tablapro.addCell(pro6);
     
     for (int i = 0; i<Tabla.getRowCount(); i++) {
                String id=Tabla.getValueAt(i, 0).toString();
                String nombre=Tabla.getValueAt(i, 1).toString();
                String precio=Tabla.getValueAt(i, 2).toString();
                String cantidad=Tabla.getValueAt(i, 3).toString();
                String marca=Tabla.getValueAt(i, 4).toString();
                String subtotal=Tabla.getValueAt(i, 5).toString();
                        
                tablapro.addCell(id);
                tablapro.addCell(nombre);
                tablapro.addCell(precio);
                tablapro.addCell(cantidad);
               
                tablapro.addCell(subtotal);
                tablapro.addCell(marca);
             }
             
    
    doc.add(tablapro);
    
    
       Paragraph total = new Paragraph();
   total.add(Chunk.NEWLINE);
   //formato a textbox total
            DecimalFormatSymbols simbolos = new DecimalFormatSymbols(Locale.US); // Locale.US utiliza punto como separador decimal        
            DecimalFormat formatototal = new DecimalFormat("0.00",simbolos);// da formato de 2 decimales luego del punt
        // Formatea el número double de total productos
        String resultadototal = formatototal.format(suma);
   
   
   
   
   total.add("Total :      "+resultadototal);
  
   
   
   
   
   doc.add(total);
             
  
   
  
  
    
    

    doc.close();
    archivo.close();
    
    
    
    
    
         }catch(Exception e){
             System.out.println(e);
         }
       
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    //------------------------funciones  crud
   
    
    
    //funcion llenar tabla
    void consultar(){
    String sql="select * from producto";
   
    
    try{
        
        conet=con1.getConnection();
        st= conet.createStatement();
        rs= st.executeQuery(sql);
        Object[]producto = new Object[7];
   
        modelo=(DefaultTableModel) Tabla.getModel();
        while(rs.next()){   
        producto[0]=rs.getInt("id");
        producto[1]=rs.getString("nombre");
        producto[2]=rs.getString("precio");
        producto[3]=rs.getString("cantidad");
        producto[4]=rs.getString("marca");
        producto[5]=rs.getInt("precio")*rs.getInt("cantidad");
        
        suma=suma+rs.getInt("precio")*rs.getInt("cantidad");
        
   
        producto[6]=rs.getString("fechamodificacion");  
        
        modelo.addRow(producto);
        

        }
        
        Tabla.setModel(modelo);
        
    }catch(Exception e){
    }//fin try 
    
   
    txtgrantotal.setText(String.valueOf(suma));

    }
    //funcion agregar dato
    void agregar(){
      //extraer hora----------------
        String fechahora = DateTimeFormatter.ofPattern("MMM/dd/yyyy HH:mm:ss a ")
     
                    .format(LocalDateTime.now());    
       
    String nombre= txtnombre.getText();
    String precio= txtprecio.getText();
    String cant= txtcantidad.getText();
    String marca=txtmarca.getText();
    
    try{
        
    if (nombre.equals("")|| precio.equals("")||cant.equals("")||marca.equals("")){
    JOptionPane.showMessageDialog(null,"Faltan campos por rellenar");
    }else{
        String sql="insert into producto(nombre,precio,cantidad,marca,fechamodificacion) values('"+nombre+"','"+precio+"','"+cant+"','"+marca+"','"+fechahora+"')"; 
        conet=con1.getConnection();
        st= conet.createStatement();
        st.executeUpdate(sql);
              
        JOptionPane.showMessageDialog(null,"Nuevo producto agregado");
         limpiar(); 
    }//fin if
        
                
    
    }catch(Exception e){
    
    }//fin catch
        
  
    }
    //funcion limpiar tabla 
    void limpiar(){
    
    for (int i =0; i<= Tabla.getRowCount();i++){
    modelo.removeRow(i);
    i=i-1;
    }
    }
    //funcion editar registro
    void modificar(){
    //extraer hora----------------
        String fechahora = DateTimeFormatter.ofPattern("MMM/dd/yyyy")
     
                    .format(LocalDateTime.now());        
           
    String nombre= txtnombre.getText();
    String precio= txtprecio.getText();
    String cantidad= txtcantidad.getText();
    String marca=txtmarca.getText();
    String id=txid.getText();
   
   
    
    try{
        
    if (nombre.equals("")|| precio.equals("")||cantidad.equals("")){
    JOptionPane.showMessageDialog(null,"Faltan campos por rellenar");
    }else{
       
       
        String sql="Update producto SET nombre='"+nombre+"',precio='"+precio+"',cantidad='"+cantidad+"',marca='"+marca+"',fechamodificacion='"+fechahora+"' WHERE id='"+id+"' "; 
        conet=con1.getConnection();
        st= conet.createStatement();
        st.executeUpdate(sql);
              
        JOptionPane.showMessageDialog(null,"Producto Modificado");
         limpiar(); 
        
        
      
    }//fin if
        
                
    
    }catch(Exception e){
    
    }//fin catch
        
  
    }
    
    void eliminar(){
   // String nombre= txtnombre.getText();
    //String precio= txtprecio.getText();
    //String cantidad= txtcantidad.getText();
    //String fechav=txtfechav.getText();
    String id=txid.getText();
    
    try{
        
    if (id.equals("")){
    JOptionPane.showMessageDialog(null,"ingrese el id a eliminar");
    }else{
        String sql="Delete From producto WHERE id ='"+id+"'"; 
        conet=con1.getConnection();
        st= conet.createStatement();
        st.executeUpdate(sql);
              
        JOptionPane.showMessageDialog(null,"Producto eliminado");
         limpiar(); 
    }//fin if
        
                
    
    }catch(Exception e){
    
    }//fin catch
        
  
    }
    
    //-----------------------fin funciones
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton agregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txid;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JLabel txtgrantotal;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
