/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PARCIAL2.sistema;
import PARCIAL2.conexion;
import PARCIAL2.ExportarExcel;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;





/**
 *
 * @author braya
 */
public class ventas extends javax.swing.JInternalFrame {

    
    conexion con1 = new conexion();
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    double totalproductos;
    
    
    
    /**
     * Creates new form ventas
     */
    public ventas() {
        initComponents();
          //funcion de colocar texto en cajas de texto desde la tabla
        Tabla.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {

                    txtnombre.setText(Tabla.getValueAt(Tabla.getSelectedRow(), 0).toString());
                    txtinventarios.setText(Tabla.getValueAt(Tabla.getSelectedRow(), 3).toString());

                }

            }

        });
        //fin funcion colocar texto

        //funcion de realizar la operacion de cambio 
        txtefectivo.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                // acción que realizar al presionar Enter en el txtefectivo
                
            String efectivo=txtefectivo.getText();
            double pagoproducto=Double.parseDouble(efectivo);
            double cambio;
            
            
            cambio=pagoproducto-totalproductos;
            
            
         DecimalFormatSymbols simbolos = new DecimalFormatSymbols(Locale.US); // Locale.US utiliza punto como separador decimal        
            DecimalFormat formato = new DecimalFormat("0.00",simbolos);// da formato de 2 decimales luego del punto

            
            
            
        
        // Formatea el número double
        String resultado = formato.format(cambio);

            
            
            
                
               txtcambio.setText(String.valueOf(resultado));
                
                
                
            }
        });
        //fin funcion cambio

        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtefectivo = new javax.swing.JTextField();
        txtbuscarproducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtcambio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        txtnombrecajero = new javax.swing.JTextField();
        txttelefonocli = new javax.swing.JLabel();
        txtnombrecli = new javax.swing.JTextField();
        txtdireccioncli = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtinventarios = new javax.swing.JTextField();
        txtdpicli = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaventa = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("FACTURA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("DESACER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio Uni.", "Marca", "Inventario", "Codigo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Efectivo ");

        txtbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarproductoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Cambio");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("PRODUCTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtcambio.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Total :");

        txttotal.setEditable(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cajero :");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("LIMPIAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cliente :");

        txtnombrecajero.setEditable(false);

        txttelefonocli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttelefonocli.setText("Telefono :");

        txtnombre.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Dirección :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Stock :");

        txtinventarios.setForeground(new java.awt.Color(204, 204, 204));
        txtinventarios.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Dpi :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nombre Producto :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad :");

        jPanel1.setBackground(new java.awt.Color(24, 186, 199));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("VENTAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(903, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("VENTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Producto", "Precio Uni.", "Sub Total"
            }
        ));
        jScrollPane2.setViewportView(tablaventa);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtinventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtbuscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtdireccioncli))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel2))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtnombrecajero)
                                            .addComponent(txtnombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txttelefonocli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtdpicli, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombrecajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txttelefonocli)
                                .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtnombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtdpicli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtdireccioncli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtcambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(txtbuscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtinventarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        actualizardb();
        pdf();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = tablaventa.getSelectedRow();

        // Verificar si se seleccionó una fila válida
        if (filaSeleccionada != -1) {
            // Obtener el modelo de la tabla
            DefaultTableModel modelo = (DefaultTableModel) tablaventa.getModel();
                
             double cancelarventa=Double.valueOf(tablaventa.getValueAt(tablaventa.getSelectedRow(), 3).toString());
            System.out.println(cancelarventa);
            
            
            // Eliminar la fila seleccionada del modelo de la tabla
            modelo.removeRow(filaSeleccionada);

            // Notificar al modelo que se realizaron cambios en los datos
            modelo.fireTableDataChanged();
            
          totalproductos=totalproductos-cancelarventa;
          txttotal.setText(String.valueOf(totalproductos));
            
            
          
          
            
            
        } else {
            // Mostrar un mensaje de error si no se seleccionó ninguna fila
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para eliminar.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarproductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        consultar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        venta();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
DefaultTableModel model = (DefaultTableModel) tablaventa.getModel();

// Elimina todas las filas del modelo-tabla de ventas
model.setRowCount(0);

    
    //limpiar datos cliente anterior
    totalproductos =0;
    txttotal.setText("");
    txtnombrecli.setText("");
    txtdireccioncli.setText("");
    txttel.setText("");
    txtdpicli.setText("");
    txtefectivo.setText("");
    txtcambio.setText("");
    
    
    
    
    
    
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       //limpia la tabla buscar producto
DefaultTableModel model = (DefaultTableModel) Tabla.getModel();

// Elimina todas las filas del modelo
model.setRowCount(0);
txtbuscarproducto.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    
    //funciones
     void consultar() {
        String sql = "SELECT nombre,precio,marca,cantidad,id FROM producto WHERE id = '"+txtbuscarproducto.getText()+"' OR  nombre LIKE '%" + txtbuscarproducto.getText() + "%'";

        try {

            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] producto = new Object[5];

            modelo = (DefaultTableModel) Tabla.getModel();
            
            while (rs.next()) {
                producto[0] = rs.getString("nombre");
                producto[1] = rs.getString("precio");
                producto[2] = rs.getString("marca");
                producto[3] = rs.getString("cantidad");
                producto[4] = rs.getString("id");
                modelo.addRow(producto);
                

            }

            Tabla.setModel(modelo);

        } catch (Exception e) {
            System.out.println("error" + e);
        }//fin try 

    }
    //fin consultar

    //-------boton agregar producto
    void venta() {
        String sql = "SELECT nombre,precio,marca,cantidad,id FROM producto WHERE nombre='" + txtnombre.getText() + "'";
        String cantidad = txtcantidad.getText();
        double cant = Double.parseDouble(cantidad);
        double subtotal=0; 
        try {

            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] producto = new Object[4];

            modelo = (DefaultTableModel) tablaventa.getModel();
            while (rs.next()) {
                producto[0] = txtcantidad.getText();
                producto[1] = rs.getString("nombre");
                producto[2] = rs.getString("precio");
                producto[3] = rs.getDouble("precio") * cant;
                modelo.addRow(producto);
                subtotal=subtotal+rs.getDouble("precio") * cant;
                
            }
            
            
            totalproductos=totalproductos+subtotal;
            
            
            
            
            
            //formato a textbox total
            DecimalFormatSymbols simbolos = new DecimalFormatSymbols(Locale.US); // Locale.US utiliza punto como separador decimal        
            DecimalFormat formatototal = new DecimalFormat("0.00",simbolos);// da formato de 2 decimales luego del punt
        // Formatea el número double de total productos
        String resultadototal = formatototal.format(totalproductos);
                txttotal.setText(String.valueOf(resultadototal));
            
            
            tablaventa.setModel(modelo);    
        } catch (Exception e) {
            System.out.println("error" + e);
        }//fin try 
    }
    //----------------------------

     void pdf() {
         try{
    FileOutputStream archivo;
   //colocar datos al pdf facturas
     
    String cliente=txtnombrecajero.getText();
    String cajero=txtnombrecli.getText();
    
    String datos=cliente+cajero+".pdf";
    //--------------
    File file= new File("C:\\Users\\braya\\Documents\\NetBeansProjects\\PIIB\\build\\classes\\pdf\\Ventas\\"+datos);
    archivo= new FileOutputStream(file);
    Document doc = new Document();
    PdfWriter.getInstance(doc, archivo);
    doc.open();
    Image img = Image.getInstance("C:\\Users\\braya\\Documents\\NetBeansProjects\\PIIB\\build\\classes\\PARCIAL2\\iconos\\copia.png");
    
    Paragraph fecha = new Paragraph();
    Font negrita= new Font(Font.FontFamily.TIMES_ROMAN,12, Font.BOLD,BaseColor.BLUE);
    fecha.add(Chunk.NEWLINE);
    Date date=new Date();
    fecha.add("Fecha: "+ new SimpleDateFormat("dd-mm-yyyy").format(date)+"\n\n");
    
    //numero de columas
    PdfPTable Encabezado = new PdfPTable(4);
    //tamano del encabezado 100 es toda la hoja
    Encabezado.setWidthPercentage(100);
    //sin bordes =0
    Encabezado.getDefaultCell().setBorder(0);
    //tamano de las celdas
    float[] ColumnaEncabezado = new float[]{20f,40f,70f,40f};
    //pasamos las columnas al encabezado
    Encabezado.setWidths(ColumnaEncabezado);
    Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
    
    Encabezado.addCell(img);
    
    //datos de la empresa 
    
   String nit ="1111111111111";
   String nom="SOUND SOLUTIONS";
   String tel="11111111";
   String dir="Chimaltenango";
   String ra="Hola Mundo";
    
   Encabezado.addCell("");
   Encabezado.addCell("Nit :"+nit+"\nNombre: "+nom+"\nTelefono: "+tel+"\nDireccion: "+dir+"\nRazon: "+ra);
   Encabezado.addCell(fecha);
   doc.add(Encabezado);
    
    
   Paragraph cli = new Paragraph();
   cli.add(Chunk.NEWLINE);
   cli.add("Datos del cliente"+"\n\n");
   doc.add(cli);
  
   //tabla cliente formato
   //numro de columnas
   PdfPTable tablacli = new PdfPTable(4);
    //tamano del encabezado 100 es toda la hoja
    tablacli.setWidthPercentage(100);
    //sin bordes =0
    tablacli.getDefaultCell().setBorder(0);
    //tamano de las celdas
    float[] Columnacli = new float[]{30f,50f,30f,40f};
    //pasamos las columnas al encabezado
    Encabezado.setWidths(Columnacli);
    //alineacion de la columna
    Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
   
    PdfPCell cl1 = new PdfPCell(new Phrase("Nombre",negrita));
    PdfPCell cl2 = new PdfPCell(new Phrase("DPI",negrita));
    PdfPCell cl3 = new PdfPCell(new Phrase("Direccion",negrita));
    PdfPCell cl4 = new PdfPCell(new Phrase("Telefono",negrita));
    cl1.setBorder(0);
    cl2.setBorder(0);
    cl3.setBorder(0);
    cl4.setBorder(0);
    
    
    cl1.setBackgroundColor(BaseColor.LIGHT_GRAY);
    cl2.setBackgroundColor(BaseColor.LIGHT_GRAY);
    cl3.setBackgroundColor(BaseColor.LIGHT_GRAY);
    cl4.setBackgroundColor(BaseColor.LIGHT_GRAY);
    
    tablacli.addCell(cl1);
    tablacli.addCell(cl2);
    tablacli.addCell(cl3);
    tablacli.addCell(cl4);
    
    tablacli.addCell(txtnombrecli.getText());
    tablacli.addCell(txtdpicli.getText());
    tablacli.addCell(txtdireccioncli.getText());
    tablacli.addCell(txttel.getText());
    
    doc.add(tablacli);
    
   //tabla producto formato
   //numro de columnas
   PdfPTable tablapro = new PdfPTable(4);
    //tamano del encabezado 100 es toda la hoja
    tablapro.setWidthPercentage(100);
    //sin bordes =0
    tablapro.getDefaultCell().setBorder(0);
    //tamano de las celdas
    float[] Columnapro = new float[]{10f,50f,15f,20f};
    //pasamos las columnas al encabezado
    tablapro.setWidths(Columnapro);
    //alineacion de la columna
    tablapro.setHorizontalAlignment(Element.ALIGN_LEFT);
   
    PdfPCell pro1 = new PdfPCell(new Phrase("Cantidad",negrita));
    PdfPCell pro2 = new PdfPCell(new Phrase("Descripcion",negrita));
    PdfPCell pro3 = new PdfPCell(new Phrase("Precio U.",negrita));
    PdfPCell pro4 = new PdfPCell(new Phrase("Sub total",negrita));
    
    pro1.setBorder(0);
    pro2.setBorder(0);
    pro3.setBorder(0);
    pro4.setBorder(0);
    //colores para las columnas
    pro1.setBackgroundColor(BaseColor.LIGHT_GRAY);
    pro2.setBackgroundColor(BaseColor.LIGHT_GRAY);
    pro3.setBackgroundColor(BaseColor.LIGHT_GRAY);
    pro4.setBackgroundColor(BaseColor.LIGHT_GRAY);
    
    
    
    
    tablapro.addCell(pro1);
    tablapro.addCell(pro2);
    tablapro.addCell(pro3);
    tablapro.addCell(pro4);
    
             for (int i = 0; i<tablaventa.getRowCount(); i++) {
                String cantidad=tablaventa.getValueAt(i, 0).toString();
                String producto=tablaventa.getValueAt(i, 1).toString();
                String precio=tablaventa.getValueAt(i, 2).toString();
                String subtotal=tablaventa.getValueAt(i, 3).toString();
                
                tablapro.addCell(cantidad);
                tablapro.addCell(producto);
                tablapro.addCell(precio);
                tablapro.addCell(subtotal);
             }
             
    
    doc.add(tablapro);
    
    
       Paragraph total = new Paragraph();
   total.add(Chunk.NEWLINE);
   //formato a textbox total
            DecimalFormatSymbols simbolos = new DecimalFormatSymbols(Locale.US); // Locale.US utiliza punto como separador decimal        
            DecimalFormat formatototal = new DecimalFormat("0.00",simbolos);// da formato de 2 decimales luego del punt
        // Formatea el número double de total productos
        String resultadototal = formatototal.format(totalproductos);
   
   
   
   
   total.add("Total :      "+resultadototal);
   
   doc.add(total);
    

    doc.close();
    archivo.close();
    
    
    
    
    
         }catch(Exception e){
             System.out.println(e);
         }
    }

    void actualizardb(){
    try{
     for (int i = 0; i<tablaventa.getRowCount(); i++) {
                String cantidad=tablaventa.getValueAt(i, 0).toString();
                String producto=tablaventa.getValueAt(i, 1).toString();
                //String precio=tablaventa.getValueAt(i, 2).toString();
                //String subtotal=tablaventa.getValueAt(i, 3).toString();
                
                System.out.println(producto);
                
                
                
            String sql = "UPDATE producto SET cantidad=cantidad-'"+cantidad+"'  WHERE nombre ='"+producto+"'";     
            conet = con1.getConnection();
            st = conet.createStatement();
            st.executeUpdate(sql);
                
     }
     }catch(Exception e){
             System.out.println(e);
             }     //fin try catch 
        
    }//fin actualizar
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaventa;
    private javax.swing.JTextField txtbuscarproducto;
    private javax.swing.JTextField txtcambio;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtdireccioncli;
    private javax.swing.JTextField txtdpicli;
    private javax.swing.JTextField txtefectivo;
    private javax.swing.JTextField txtinventarios;
    private javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtnombrecajero;
    private javax.swing.JTextField txtnombrecli;
    private javax.swing.JTextField txttel;
    private javax.swing.JLabel txttelefonocli;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
